version: "3"

services:
  reviewDB:
    image: cassandra:latest
    ports:
      - "9160:9160"

  review:
    build: .
    environment:
      WAIT_HOSTS: reviewDB:9160
    ports:
      - "80:3000"
    depends_on:
      - reviewDB
