version: "3"

services:
  reviewDB:
    image: cassandra:latest
    ports:
      - "9042:9042"

  review:
    # image: hanlinaunghack/sdcreview1atest
    build: .
    environment:
      WAIT_HOSTS: reviewDB:9042
    ports:
      - "80:3000"
      - "9042:9042"
    depends_on:
      - reviewDB
